わかる範囲でカキました
tsukuba-cojt/tsukuba-cojt.github.io pull request #31
Opened 2022-06-24 08:35 UTC by Chiji0503

2022-07-01 05:21 UTC, takonasu commented
@Chiji0503 何かしらの画像を用意してください。

2022-07-08 07:13 UTC, Chiji0503 commented
@takonasu 変更しました

2022-07-08 07:21 UTC, takonasu requested changes
src/image/logo.png
src/results/sample-team.md
が消されてしまっていますが、上記ファイルはサンプルのため消さないでください。

2022-07-08 07:22 UTC, takonasu commented
@Chiji0503

2022-07-08 07:28 UTC, Chiji0503 commented
すみません、mdのサンプルをどこから復元すればよいか教えていただけますでしょうか

2022-07-08 07:45 UTC, Chiji0503 commented
@takonasu sampleを復元できたのでpushしました

2022-07-08 07:46 UTC, takonasu approved these changes
返信気づかなかった申し訳ない、OKいい感じ！

2022-07-08 07:51 UTC, merged