Music game team
tsukuba-cojt/tsukuba-cojt.github.io pull request #58
Opened 2022-07-20 03:27 UTC by seisyun9665

概要や操作方法の文章の追記や画像の更新など、サイト内容の更新を行いました。

2022-07-20 05:56 UTC, nbz16 commented
@seisyun9665 アイコン画像を正方形になるように調整をお願いします．

2022-07-21 04:31 UTC, seisyun9665 commented
修正しました

2022-07-22 07:08 UTC, takonasu commented
@seisyun9665 フォルダーに格納したものの使われていない画像があるようですが大丈夫ですか？

2022-07-22 07:14 UTC, takonasu requested changes
使用していない不要なファイル（画像ファイル等）は消去してください

2022-07-22 07:27 UTC, takonasu approved these changes
OKです、お疲れ様です！

2022-07-22 07:37 UTC, merged