wifiハックチームのmdファイルを作成しました
tsukuba-cojt/tsukuba-cojt.github.io pull request #94
Opened 2023-01-20 08:44 UTC by shunsuke0424

未入力な項目があります。今後埋めていく予定です。

2023-01-23 01:17 UTC, Hidetaro7 commented on src/results/wifi-hack-team.md
> +term: fall
```suggestion
term: autumn
```

fallでも正しいですが、ここは全体のトーンを合わせたいのでautumnとさせてください

2023-01-27 07:04 UTC, takonasu commented
Slackに共有した事項への対応をお願いしますmm

2023-02-01 07:09 UTC, takonasu commented on src/results/2022autumn/wifi-hack-team.md
> +icon: "/image/results/2022autumn/wifi-hack/icon.png"
iconとcoverのファイルパスが間違えているので修正してください

2023-02-01 07:10 UTC, takonasu requested changes
マークダウン中のアイコンとカバーのパス名が間違えているので修正してください

2023-02-01 14:07 UTC, takonasu commented
@shunsuke0424 レイアウトが崩れているように見えますが大丈夫ですか？
https://tsukuba-cojt-github-io-git-wifihackteam-takonasu.vercel.app/results/2022autumn/wifi-hack-team/

2023-02-02 10:34 UTC, Hidetaro7 commented on src/results/2022autumn/wifi-hack-team.md
> +### 概要
```suggestion
## 概要
```

見出しレベルがh3に落ちていますが、他の見出しと並列に並べてください。

2023-02-02 10:35 UTC, Hidetaro7 commented on src/results/2022autumn/wifi-hack-team.md
> +### 実装
```suggestion
## 実装
```

2023-02-02 10:36 UTC, Hidetaro7 commented on src/results/2022autumn/wifi-hack-team.md
> +# 使用される技術:
```suggestion
### 使用される技術:
```

ここが h1 になっているのが違和感でした。
「h2: 実装」というセクションの中で「h3: 使用される技術」というアウトラインが構成されたほうが自然だと感じます。

2023-02-02 10:36 UTC, Hidetaro7 commented on src/results/2022autumn/wifi-hack-team.md
> +# ユーザインターフェイス(UI):
```suggestion
### ユーザインターフェイス(UI):
```

2023-02-02 10:37 UTC, Hidetaro7 commented on src/results/2022autumn/wifi-hack-team.md
> +### 今後の展望
```suggestion
## 今後の展望
```

ここは「実装」のセクションではないように思われますのでh2を提案します。

2023-02-03 01:09 UTC, Hidetaro7 commented
いいですね、マークダウン構成は問題なくなったと思います。

2023-02-03 01:17 UTC, takonasu approved these changes
お疲れ様です！

2023-02-03 05:10 UTC, merged