カードゲームです
tsukuba-cojt/tsukuba-cojt.github.io pull request #95
Opened 2023-01-20 08:45 UTC by Hakumai-OI-C

2023-01-23 01:16 UTC, Hidetaro7 commented on src/results/security_card.md
> +term: spring
```suggestion
term: autumn
```

秋学期ということで、autumnでお願いします。

2023-02-01 07:06 UTC, takonasu requested changes
画像は
`/src/image/results/2022/autumn/`
マークダウンは
`/src/results/2022autumn`
にcscディレクトリを作成してください！

2023-02-01 14:08 UTC, takonasu requested changes
パスの修正をお願いします

2023-02-01 14:08 UTC, takonasu commented on src/results/2022autumn/SecurityCardGame/security_card.md
> +cover: "/image/results/2022/csc/csc_cover.png"
iconとcoverの
パスが間違えているので修正してください！

2023-02-02 10:27 UTC, Hidetaro7 commented on src/results/2022autumn/SecurityCardGame/security_card.md
> +このゲームは、遊びながら楽しく情報セキュリティについて学ぶことを目的としたカードゲームです。
このあたりの改行が反映されていないのは意図的ですか？
改行したい場合は半角スペース2つでマークダウンでは改行されますが、おまかせします。

2023-02-02 10:29 UTC, takonasu approved these changes
秋葉さんご指摘の箇所が問題ない場合はマージして大丈夫です！

2023-02-02 17:54 UTC, merged